inputs_def:
  - handle: image
    description: "Image file to perform OCR on"
    json_schema:
      type: string
      ui:
        widget: file
        options:
          filters:
            - name: Images
              extensions:
                - png
                - jpg
                - jpeg
                - bmp
                - tiff
                - webp
          excludeAll: true
    nullable: false

  - handle: resolution
    description: "Resolution mode for OCR processing"
    json_schema:
      type: string
      enum:
        - tiny
        - small
        - base
        - large
        - gundam
      default: base
    nullable: false
    value: base

  - handle: prompt
    description: "Custom prompt for OCR task"
    json_schema:
      type: string
      default: "Transcribe the text in this image"
    nullable: false
    value: "Transcribe the text in this image"

  - handle: use_gpu
    description: "Use GPU acceleration (CUDA) for processing"
    json_schema:
      type: boolean
      default: true
    nullable: false
    value: true

outputs_def:
  - handle: text
    description: "Extracted text from the image"
    json_schema:
      type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "DeepSeek OCR"
icon: ":carbon:document-tasks:"
description: "Extract text from images using DeepSeek-OCR vision-language model. Supports multiple resolution modes and GPU acceleration."
